[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'crusoexia/vim-monokai'
# repo = 'sickill/vim-monokai'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'eed3si9n/LanguageClient-neovim'

# [[plugins]]
# repo = 'prabirshrestha/async.vim'

# [[plugins]]
# repo = 'prabirshrestha/vim-lsp'

