[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'derekwyatt/vim-scala'

# [[plugins]]
# repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'mfussenegger/nvim-dap'

[[plugins]]
repo = 'scalameta/nvim-metals'

[[plugins]]
repo = 'hrsh7th/nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

# [[plugins]]
# repo = 'eed3si9n/LanguageClient-neovim'

# [[plugins]]
# repo = 'prabirshrestha/async.vim'
