[[plugins]]
repo = 'junegunn/fzf'
merged = 0
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
" map <Leader>f to opening files
nnoremap <silent> <Leader>f :<C-U>:Files<CR>
nnoremap <silent> <Leader>b :<C-U>:Buffers<CR>
nnoremap <silent> <Leader>/ :<C-U>:Rg<SPACE>

let g:fzf_layout = { 'up': '40%' }

" add layout=reverse to all the commands
command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'options': ['--layout=reverse', '--info=inline']}), <bang>0)
command! -bar -bang -nargs=? -complete=buffer Buffers
    \ call fzf#vim#buffers(<q-args>, { 'placeholder': '{1}', 'options': ['-d', '\t', '--layout=reverse'] })
command! -bang -nargs=* Rg
    \ call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case -- ".shellescape(<q-args>), 1, {'options': ['--layout=reverse', '--info=inline']}, <bang>0)
'''

[[plugins]]
repo = 'Shougo/defx.nvim'

hook_add = '''
nnoremap <silent> <Leader>e :<C-U>:Defx -resume -buffer_name=explorer -split=vertical -vertical_preview<CR>

nnoremap <silent> - :<C-U>:Defx `expand('%:p:h')` -search=`expand('%:p')` -buffer-name=defx<CR>

autocmd FileType defx call s:defx_my_settings()
function! s:defx_my_settings() abort
  " Define mappings
  nnoremap <silent><buffer><expr> <CR>
  \ defx#is_directory() ?
  \ defx#do_action('open_tree', 'recursive:10') :
  \ defx#do_action('preview')
  nnoremap <silent><buffer><expr> b
  \ defx#do_action('multi', ['close_tree', 'close_tree', 'close_tree', 'close_tree', 'close_tree', 'close_tree', 'close_tree', 'close_tree', 'close_tree', 'close_tree'])
  nnoremap <silent><buffer><expr> o
  \ match(bufname('%'), 'explorer') >= 0 ?
  \ (defx#is_directory() ? 0 : defx#do_action('drop', 'vsplit')) :
  \ (defx#is_directory() ? 0 : defx#do_action('multi', ['open', 'quit']))
  nnoremap <silent><buffer><expr> l
  \ defx#is_directory() ? defx#do_action('open') : 0
  nnoremap <silent><buffer><expr> h
  \ defx#do_action('cd', ['..'])
  nnoremap <silent><buffer><expr> K
  \ defx#do_action('new_directory')
  nnoremap <silent><buffer><expr> N
  \ defx#do_action('new_file')
  nnoremap <silent><buffer><expr> d
  \ defx#do_action('remove')
  nnoremap <silent><buffer><expr> r
  \ defx#do_action('rename')
  nnoremap <silent><buffer><expr> q
  \ defx#do_action('quit')
endfunction
'''

hook_post_source = '''
call defx#custom#option('_', {
\ 'winwidth': 50,
\ 'ignored_files': '.*,target*',
\ 'direction': 'topleft',
\ 'toggle': 1,
\ 'columns': 'indent:git:icons:filename:mark',
\ })
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

hook_post_source = '''
call airline#parts#define_function('metals', 's:metals_status')
let g:airline_section_warning (metals)

function! s:metals_status() abort
  return get(g:, 'metals_status', '')
endfunction
'''

# [[plugins]]
# repo = 'scrooloose/nerdtree'
# hook_add = '''
#    nnoremap <silent> <Leader>e :<C-U>:NERDTreeToggle<CR>
# '''

# [[plugins]]
# repo = 'wincent/command-t'

# hook_add = '''
# nnoremap <silent> <Leader>t :<C-U>:CommandT<CR>
# '''

## cd ~/.cache/dein/repos/github.com/wincent/command-t/
## cd ruby/command-t/ext/command-t
## make clean && ruby extconf.rb && make
